# Generated by Django 4.2.6 on 2023-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='apelido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
    ]
