# Generated by Django 4.2.6 on 2023-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_contato_apelido_alter_contato_complemento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='contato',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'solteiro'), ('C', 'casado'), ('D', 'Divorciado'), ('V', 'viúvo')], max_length=1, null=True),
        ),
    ]
