# Generated by Django 4.2.7 on 2023-11-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0003_alter_contato_options_contato_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascença'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
