# Generated by Django 4.2.6 on 2023-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0010_interesse_alter_telefone_ddd_alter_telefone_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='Interesse',
            field=models.ManyToManyField(to='AgendaApp.interesse'),
        ),
    ]
